# Generated by Django 4.2.5 on 2023-11-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='massage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phonnumber', models.IntegerField()),
                ('titl', models.CharField(max_length=30)),
                ('body', models.TextField()),
            ],
        ),
    ]
