# Generated by Django 4.2.5 on 2024-01-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_article_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='alaki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'الکی',
                'verbose_name_plural': 'الکی ها',
            },
        ),
    ]
